### ISSUE TITLE
Build warnings against v14

### ISSUE THREAD

**Issue by devrimgunduz** [okbob/pgexportdoc#3]
Hi,

0.1.3 is throwing warnings while building against v14. Can you please take a look? Thanks! Devrim

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/pgsql-14/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgexportdoc.bc pgexportdoc.c
pgexportdoc.c:97:3: warning: implicit declaration of function 'simple_prompt' is invalid in C99 [-Wimplicit-function-declaration]
                simple_prompt("Password: ", password, sizeof(password), false);
                ^
pgexportdoc.c:153:4: warning: implicit declaration of function 'simple_prompt' is invalid in C99 [-Wimplicit-function-declaration]
                        simple_prompt("Password: ", password, sizeof(password), false);
                        ^
2 warnings generated.
pgexportdoc.c: In function 'pgexportdoc':
pgexportdoc.c:97:17: warning: implicit declaration of function 'simple_prompt' [-Wimplicit-function-declaration]
   97 |                 simple_prompt("Password: ", password, sizeof(password), false);
      |                 ^~~~~~~~~~~~~
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection pgexportdoc.o   -L/usr/pgsql-14/lib  -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-14/lib',--enable-new-dtags  -L/usr/pgsql-14/lib -lpgcommon -lpgport -L/usr/pgsql-14/lib -lpq -lpgcommon -lpgport -lselinux -llz4 -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lpthread -lrt -ldl -lm  -o pgexportdoc
pgexportdoc.c:97:17: warning: type of 'simple_prompt' does not match original declaration [-Wlto-type-mismatch]
   97 |                 simple_prompt("Password: ", password, sizeof(password), false);
      |                 ^
../../../../../../../../../../../../../../var/lib/pgsql/rpm14testing/BUILD/postgresql-14beta1/src/common/sprompt.c:38:1: note: return value type mismatch
../../../../../../../../../../../../../../var/lib/pgsql/rpm14testing/BUILD/postgresql-14beta1/src/common/sprompt.c:38:1: note: 'simple_prompt' was previously declared here
../../../../../../../../../../../../../../var/lib/pgsql/rpm14testing/BUILD/postgresql-14beta1/src/common/sprompt.c:38:1: note: code may be misoptimized unless '-fno-strict-aliasing' is used
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pgexportdoc/master/pgexportdoc-0.1.3'
a

**Comment by okbob** [comment]
Should be fixed now, please check.

**Comment by devrimgunduz** [comment]
@okbob great, thank you! I'll RPMify them when you push a new release.

Regards, Devrim

**Comment by okbob** [comment]
po 7. 6. 2021 v 17:04 odesílatel Devrim Gündüz ***@***.***>
napsal:

> @okbob <https://github.com/okbob> great, thank you! I'll RPMify them when
> you push a new release.
>

I thank you

Pavel

**Comment by devrimgunduz** [comment]
@okbob can you please release a new version? v14 is around the corner now.

**Comment by okbob** [comment]
https://github.com/okbob/pgexportdoc/releases/tag/0.1.4

Thank you for remind

**Comment by devrimgunduz** [comment]
Thanks a lot! Cheers.
